### ISSUE TITLE
Developer installation instructions

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#111]
I took notes while installing the development environment on Windows 10 during our Crick hackathon. These notes might be useful for future contributors with limited knowledge of the C++ ecosystem

* download cmake from cmake.org
  * while installation make cmake accessible within PATH
* download and install vs code from https://code.visualstudio.com/
* install VS code extensions
  * "CMAKE Tools" from Microsoft
  * "Cmake integration" from Christoph Seitz
  * "C/C++ Extension Pack" from microsft
* Restart VS Code
* install git in your base environment (and have it accessible from the PATH)
  * `conda install git`
* Download and install Visual Studio Community Edition from https://visualstudio.microsoft.com/
  * Activate "Desktop development with C++"

![image](https://user-images.githubusercontent.com/12660498/203598129-8064bcd9-f7bb-49ed-890f-413014b9dad7.png)

**Comment by haesleinhuepf** [comment]
Notes from Mac instructions:

* `brew install cmake`

**Comment by StRigaud** [comment]
I think you already started a doc for windows user: 
- [windows build](https://github.com/clEsperanto/CLIc_prototype/blob/master/docs/windows_build/windows_build.md)

Maybe better to continue from this one, and do the same for the other OSs?

**Comment by StRigaud** [comment]
Instruction are now provided in https://clesperanto.github.io/CLIc/
The doc can be extended through PR, feel free to add what you believe is necessary by updating the `docs` folder content.
