### ISSUE TITLE
Test a function using a specified GPU

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#241]
I'm currently trying to execute a test on a specified GPU (on Windows). After building CLIc, I copied over the `install_folder/*.dll` files to `build/tests/tier7/` to make the `test_voronoi_otsu_labeling.exe` execute. The test runs fine. I would like to switch the GPU now. Is this described in the documentation somewhere?

**Comment by haesleinhuepf** [comment]
Maybe, we could add a test - or some page in the documentation - that does something like this script:

https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/basics/select_GPU.py

**Comment by StRigaud** [comment]
closed with #269
