### ISSUE TITLE
Feature request: function to smooth external labels

### ISSUE THREAD

**Issue by kevinyamauchi** [clEsperanto/CLIc#249]
Hello! I think it would be cool to have a function that smooths external labels. By that, I mean just smooth the labels touching background while leaving the interfaces between segments the same.

For context, this would be helpful to me as we do a lot of mechanical simulations where we make meshes of cells as input to the simluation. The meshes should be smooth and this is easier to achieve when the labels are smooth. The `smooth_labels` function in `pyclesperanto_prototype` works well for "internal labels" (i.e., boundaries between cells), but in my preliminary testing, doesn't seem to smooth the external boundary of the cells (I think due to [this line](https://github.com/clEsperanto/CLIc/blob/f8a432b30d9f5747f06b1101b87488a38caff341/clic/src/tier8.cpp#L27)).

Perhaps something like:

1. dilate all pixels that have a neighboring background pixel (e.g., value 0)
2. erode all pixels that have a neighboring background pixel (e.g., value 0)

I naively first tried just dilating than eroding the labels (and the other way around) and the issue is that that the interfaces between the cells also get modified and sometimes this leads to gaps, etc.

What do you all think?

**Comment by StRigaud** [comment]
If i understood well:
You have a set of labels
You want to smooth them but only the perimeter in contact with the background

My quick guess would be to:
- binaries the label into a mask
- smooth the mask
- reapply the labels on the mask

would that work?

**Comment by kevinyamauchi** [comment]
Yes, sounds like that could work!

**Comment by StRigaud** [comment]
I will have a look at it then!

**Comment by kevinyamauchi** [comment]
Cool, thanks!

**Comment by StRigaud** [comment]
I added a filter, very similar to the `smooth_labels` but here only the binary version of the labels are smoothed using a closing and an opening operation.

I'm open for better function name, as well as considering merging it with the `smooth_labels` function.

**Comment by haesleinhuepf** [comment]
Hi @kevinyamauchi ,

I _think_ your use-case is covered with the function `erode_connected_labels` in combination with `dilate_labels`. You find an example notebook here:
https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20h_segmentation_post_processing/erode_connected_labels.html

Please let us know if this works for you! We could then implement `erode_connected_labels` in CLIc too.

Thanks!

Best,
Robert

**Comment by kevinyamauchi** [comment]
Hey @haesleinhuepf ! I hadn't seen `erode_connected_labels` before. This in combination with `dilate_labels` is indeed helpful for my usecase.

#262 looks like it will be super useful. Thanks, @StRigaud !

**Comment by StRigaud** [comment]
Great!

The erode_connected_labels will be available in the next version 😃
