### ISSUE TITLE
tier1::multiply_image_and_position_func() implicitly assumes that the position has the same type as the input.

### ISSUE THREAD

**Issue by thawn** [clEsperanto/CLIc#287]
currently, tier1::multiply_image_and_position_func() implicitly assumes that the position has the same type as the input, while it is actually of type uint32 (or even uint64?).

This is the root cause of [bug 164 in pyclesperanto](https://github.com/clEsperanto/pyclesperanto/issues/164).

**Comment by StRigaud** [comment]
should be fixed with 
- #288
