### ISSUE TITLE
Github OSx runner cannot run tests anymore

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc#290]
It seems that the OSx runner from the Github CI now fail to run OpenCL operations.
See: 
- #289 
- #288 

The runner was used for running tests and coverage as it was easier due to the pre-availability of the OpenCL framework on the OS as well as the presence of a `device` capable of running code.

The output error is that CLIc is no more capable of finding an OpenCL device on the runner...

**Comment by kevinyamauchi** [comment]
This could be because Github Actions switched to using ARM on `macos-latest`. You might try to switch to `macos-13` switch back to Intel.

**Comment by StRigaud** [comment]
Indeed, tested with #289 and it works. Thanks @kevinyamauchi !
Would be great to be able to move the tests on Ubuntu-latest but PoCL fail to work as it does not properly identify the AMD CPU used by Github Actions :/
