### ISSUE TITLE
GPU support image format but it return `0` or `CL_IMAGE_FORMAT_NOT_SUPPORTED` 

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc#317]
in OpenCL, the `cl_image` is defined by a `cl_image_format` composed of `cl_channel_order` and `cl_channel_type`. 
- `cl_channel_type`: correspond to the data type `float`, `int8` etc, 
- `cl_channel_order`: correspond to the composition of the image `CL_RGB` for example.

Clesperanto only manage single channel image, which point to the following `channel_order`: `CL_R`, `CL_A`, `CL_INTENSITY`, or `CL_LUMINANCE`.

Eventhough they all represente a single channel image, their behaviour differe based on opencl version and hardware. Quick tests shows the following.

On my local NVIDIA card:
- `CL_A` return `0` with CLIj framework 
- `CL_R` work with all and does not replicate the values
- `CL_INTENSITY` work with all, but the value is replicated on the with channel RGB 
- `CL_LUMINANCE` work with all but the value is replicated on the with channel RGB
-
On my local M2 Apple:
- `CL_A` return `0` with CLIj framework 
- `CL_R` work with all and does not replicate the values
- `CL_INTENSITY` work only with `CL_FLOAT`, and the value is replicated on the with channel RGB 
- `CL_LUMINANCE` is not supported

This point toward the usage of the `CL_R`. I will set a PR to ensure maximum compatibility.

Classic OpenCL error that could be related to this issue is `CL_IMAGE_FORMAT_NOT_SUPPORTED`

**Comment by StRigaud** [comment]
@haesleinhuepf 

With #318, `cl_image` is fully compatible on my M2, this include the interpolation. This will be available on the python side with the next release (soon).

**Comment by haesleinhuepf** [comment]
That's super cool! And it might be an advantage over clij2 and pyclesperanto_prototype

**Comment by StRigaud** [comment]
Its possible that it is the same issue for the prototype and clij2 somewhere in the code? 

Rigth now I am trying to make the CI skip tests over images because it does not support them. Once I manage, I will merge and make a release to have both chan-vese and affine transform operational

**Comment by StRigaud** [comment]
Test involving images are always skip.
To enable them for local test, one must comment `GTEST_SKIP()` in the test code.

Its not great but will do for now
