### ISSUE TITLE
push/pull terminoloy

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#322]
I'm a bit confused about terminology in CLIC. I found this code snippet:

https://github.com/clEsperanto/CLIc/blob/679bd1b03cad33d959bcb0c62c607793aa209396/tests/tier1/test_absolute.cpp#L30-L33

I'm having a little trouble understanding the last line. Is `gpu_output` read from `output` or is its content written to `output`? Would it be possible to use the push/pull terminology we used in clij? Alternatively, could the functions be renamed to "read_from" or "write_to" to improve readability of code?

**Comment by StRigaud** [comment]
`push/pull` for me are more related to the user functionnality. I started to do something like that in `memory.hpp` but never used it. 

CLIc is more low level and require a bit more control and coding. I found the `read/write` more adapted. I am ok though to update their name with a directionnality `from/to`.

**Comment by haesleinhuepf** [comment]
Alright. We also had "writeTo" in [CLearCL](https://github.com/clij/clij-clearcl), the former backend. That makes a lot of sense.

**Comment by StRigaud** [comment]
More sense would be `CopyTo` and `CopyFrom` has we copy `mem` between host and device. This is how it is done in `pyopencl`.

But laizy to change again for now. I merge the PR changing this, so I will close this Issue and you can already start using the new naming :)
