### ISSUE TITLE
threshold_otsu does not work as expected for floating point images with very small values

### ISSUE THREAD

**Issue by thawn** [clEsperanto/CLIc#342]
cle.threshold_otsu gives wrong segmentations for float32 images with very small values (<0,003)

example: 
```python
image = np.array([[0,0,0],
                  [0,0.003,0],
                  [0,0,0]])

thresholded = cle.threshold_otsu(image)
```
pyclesperanto returns
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8, mtype=buffer)

pyclesperanto_prototype returns as expected
array([[0,0,0],
       [0, 1, 0],
       [0,0,0]], dtype=uint8, mtype=buffer)

a notebook for reproducing the issue is attached
[clesperanto_bug.ipynb.zip](https://github.com/user-attachments/files/16962843/clesperanto_bug.ipynb.zip)

**Comment by StRigaud** [comment]
If you increase the number it works correctly?

**Comment by StRigaud** [comment]
Also, do you know if you have the same issue with the prototype? I will test on my side, but interested if you know already the answer

**Comment by thawn** [comment]
@StRigaud thanks for looking into this :-)

yes, with larger numbers (even 0.004) it works as expected.

no the prototype does not have the same problem

**Comment by StRigaud** [comment]
Thanks! That narrow it a bit down.

Weird for the 0.004 though.

I might need a bit of time before fixing this but will try to do it quick!

**Comment by thawn** [comment]
Just in case someone else runs into this problem, scaling the image intensities to 0-255 before applying threshold_otsu works as a workaround. I am using the following code:

```python
scaled = cle.add_image_and_scalar(image, scalar=-cle.minimum_of_all_pixels(image))
scaled = cle.multiply_image_and_scalar(scaled, scalar=255 / cle.maximum_of_all_pixels(scaled))
thresholded = cle.threshold_otsu(scaled)
```

**Comment by StRigaud** [comment]
This should be fix at the next release :)

**Comment by thawn** [comment]
@StRigaud thanks a lot for fixing this bug :-)
