### ISSUE TITLE
The function "minimum" may have the wrong name or wrong parameters, depending on which function in _prototype it corresponds to.

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#370]
In Pyclesperanto_prototype, we had three functions:
* `minimum_box(source, destination, radius_x, radius_y, radius_z)`
* `minimum_sphere(source, destination, radius_x, radius_y, radius_z)`
* `minimum_images(source1, source2, destination)`

And an alias:
* `minimum` which [points at](https://github.com/clEsperanto/pyclesperanto_prototype/blob/8bd12efd32d2bcdbfc859bcfec85c7a567e17b06/pyclesperanto_prototype/_tier1/__init__.py#L98) `minimum_images`.

In pyclesperanto/clic, there is `minimum`, with these parameters:
* `minimum(input_image, output_image, radius_x, radius_y, radius_z)`

Does it make sense to rename it? E.g. "minimum_filter" would match [scipy.ndimage.minimum_filter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.minimum_filter.html)

**Comment by haesleinhuepf** [comment]
The same issue existis with `maximum` obviously.

**Comment by StRigaud** [comment]
ok for renaming to `minimum_filter` (same for max)
