### ISSUE TITLE
Parameter renaming in remove_small_labels

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#377]
Hi @StRigaud ,

I just noticed a name change, where I'm not sure if it was intentional:
In the prototype [exclude_small_labels](https://github.com/clEsperanto/pyclesperanto_prototype/blob/8bd12efd32d2bcdbfc859bcfec85c7a567e17b06/pyclesperanto_prototype/_tier4/_exclude_small_labels.py#L6) has a parameter "maximum_size".
In CLIC, [remove_small_labels](https://github.com/clEsperanto/CLIc/blob/4c18fc0efca8f2f26f86f66f15fc188a47ab0d42/clic/src/tier6/remove_objects.cpp#L16) has a parameter "minimum_size".

Is this intentional? It appear unintuitive to me. I would like to remove small labels up to a given _maximum_ size...

**Comment by StRigaud** [comment]
Hey @haesleinhuepf 

Yes, it is intentionnal: 
- https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.remove_small_objects

> It appear unintuitive to me

It's the reverse to me. I am focused on what I want, object bigger than a certain size, not what I want to remove. Though I dont think there is a correct answer here

**Comment by haesleinhuepf** [comment]
Ok. Fine. It has the older name in the exclude_... function and thus, is backwards-compatible. We should point this out in a deprecation message, once we add it. Hence, I leave this issue open so that we can cover this in the documentation.

**Comment by StRigaud** [comment]
Yup,

I will put back warning of deprecation when we will start to move to beta
